### ISSUE TITLE
i reimplemented it as a shell wrapper

### ISSUE THREAD

**Issue by sudofox** [Gankra/cargo-mommy#14]
https://github.com/sudofox/shell-mommy

hope that's alright, i reused your texts

**Comment by FWDekker** [comment]
What the... I saw cargo-mommy a month ago and I also made a shell version at https://github.com/FWDekker/mommy, but I didn't know you already made one!

But it looks like I have several features that yours doesn't have ^^' Like compatibility with all Unix systems and all shells, random/rainbow colours, configuration files, distribution as `.deb`, more template variables, etc.

Sorry if it looks like I copied you, that was not my intention :/

**Comment by Gankra** [comment]
MOMMY'S PROUD OF YOU ALL

**Comment by Zopolis4** [comment]
Created this abomination to help from transferring the responses from `cargo-mommy` over to FWDekker's implementation.

Just change the `jq` command to choose from different responses.
```
curl https://raw.githubusercontent.com/Gankra/cargo-mommy/main/responses.json | jq .moods.chill.positive | tr -d [] | sed 's/  "//g' | sed 's/",//g' | sed 's/"//g' |  sed 's/~//g' | sed 's/{role}/%%CAREGIVER%%/g' | sed 's/{affectionate_term}/%%SWEETIE%%/g' | sed 's/{pronoun}/%%THEIR%%/g'
```

Should work for most things, won't work for some of the spicier ones because there's no equivalent to `{denigrating_term}` or `{part}`.
